# Generated by Django 4.2.23 on 2025-08-03 19:49

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('average_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('first_purchase_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('broker', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-total_cost'],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('reliability_score', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('security_type', models.CharField(max_length=10)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('sic_description', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True, help_text='URL to the company/fund logo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='SmartWatchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Watchlist', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.security')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='securities.smartwatchlist')),
            ],
            options={
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('SPLIT', 'Stock Split')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=12)),
                ('price_per_share', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('fees', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='securities.holding')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('relevance', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='securities.security')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.newssource')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityFundamentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('previous_close', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('day_change', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('day_change_percent', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('avg_volume', models.BigIntegerField(blank=True, null=True)),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('news_summary', models.TextField(blank=True, help_text='High-level summary of recent news for this security')),
                ('news_summary_updated_at', models.DateTimeField(blank=True, help_text='When the news summary was last updated', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('security', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentals', to='securities.security')),
            ],
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['symbol'], name='securities__symbol_5a01a4_idx'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['security_type', 'is_active'], name='securities__securit_6dc8ab_idx'),
        ),
        migrations.AddField(
            model_name='holding',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.security'),
        ),
        migrations.AddField(
            model_name='holding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('watchlist', 'security')},
        ),
        migrations.AlterUniqueTogether(
            name='smartwatchlist',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='securitynews',
            index=models.Index(fields=['security', '-published_at'], name='securities__securit_737197_idx'),
        ),
        migrations.AddIndex(
            model_name='securitynews',
            index=models.Index(fields=['security', 'relevance', '-published_at'], name='securities__securit_af7c4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together={('user', 'security')},
        ),
    ]
