# Generated by Django 4.2.23 on 2025-08-04 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlistitem',
            options={'ordering': ['added_at']},
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='watchlistitems', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('user', 'security')},
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='position',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='target_price',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='watchlist',
        ),
        migrations.DeleteModel(
            name='SmartWatchlist',
        ),
    ]
