# Generated by Django 4.2.23 on 2025-08-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0002_alter_watchlistitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish'), ('Neutral', 'Neutral')], max_length=10)),
                ('rationale', models.TextField(help_text='Explanation for the sentiment classification')),
                ('confidence_level', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Overall Sentiment',
                'verbose_name_plural': 'Overall Sentiments',
            },
        ),
        migrations.CreateModel(
            name='SecurityNewsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField(help_text='Comprehensive 3-4 paragraph overview of recent developments')),
                ('summary', models.TextField(help_text='Quick 1-2 sentence overview of current situation')),
                ('positive_catalysts', models.TextField(help_text='2-3 paragraph summary of upside drivers')),
                ('risk_factors', models.TextField(help_text='2-3 paragraph summary of potential headwinds')),
                ('key_metrics', models.JSONField(blank=True, default=dict, help_text='Key financial metrics as key-value pairs')),
                ('disclaimer', models.TextField(help_text='Standard professional disclaimer about analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_sentiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_summaries', to='securities.overallsentiment')),
                ('security', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news_summary', to='securities.security')),
            ],
            options={
                'verbose_name': 'Security News Summary',
                'verbose_name_plural': 'Security News Summaries',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Concise, factual title', max_length=500)),
                ('date', models.DateField(help_text='Publication date of the news')),
                ('source', models.CharField(help_text='News source name', max_length=100)),
                ('url', models.URLField(help_text='URL to original article')),
                ('impact_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='Impact assessment: High, Medium, or Low', max_length=10)),
                ('summary', models.TextField(help_text='2-3 sentences explaining the news and its implications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='securities.security')),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.TextField(help_text='Individual highlight point')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for displaying highlights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security_news_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_highlights', to='securities.securitynewssummary')),
            ],
            options={
                'verbose_name': 'Key Highlight',
                'verbose_name_plural': 'Key Highlights',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(help_text='Clear description of the catalyst')),
                ('date', models.CharField(help_text="Specific date or timeframe (e.g., 'Q1 2025', 'Late February 2025')", max_length=50)),
                ('category', models.CharField(choices=[('Earnings', 'Earnings'), ('Corporate_Actions', 'Corporate Actions'), ('Regulatory', 'Regulatory'), ('Strategic', 'Strategic'), ('Industry', 'Industry'), ('Economic', 'Economic')], help_text='Event category', max_length=20)),
                ('importance', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='Importance level', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_events', to='securities.security')),
            ],
            options={
                'verbose_name': 'Upcoming Event',
                'verbose_name_plural': 'Upcoming Events',
                'ordering': ['date', '-importance'],
                'indexes': [models.Index(fields=['security', 'category'], name='securities__securit_e162f9_idx'), models.Index(fields=['security', 'importance'], name='securities__securit_c4c4c5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='securitynewssummary',
            index=models.Index(fields=['security', '-updated_at'], name='securities__securit_ae2bce_idx'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['security', '-date'], name='securities__securit_a0a289_idx'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['security', 'impact_level', '-date'], name='securities__securit_055955_idx'),
        ),
        migrations.AddIndex(
            model_name='keyhighlight',
            index=models.Index(fields=['security_news_summary', 'order'], name='securities__securit_9cd3d0_idx'),
        ),
    ]
