# Generated by Django 4.2.23 on 2025-08-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0003_overallsentiment_securitynewssummary_newsitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='holding',
        ),
        migrations.DeleteModel(
            name='SecurityNews',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
