# Generated by Django 4.2.23 on 2025-08-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0004_remove_transaction_holding_delete_securitynews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='favicon',
            field=models.URLField(blank=True, help_text='Favicon URL of the news source'),
        ),
    ]
