# Generated by Django 4.2.23 on 2025-08-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0005_newsitem_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityfundamentals',
            name='week_52_high',
        ),
        migrations.RemoveField(
            model_name='securityfundamentals',
            name='week_52_low',
        ),
        migrations.AddField(
            model_name='securityfundamentals',
            name='data_timestamp',
            field=models.BigIntegerField(blank=True, help_text='Timestamp from API data source', null=True),
        ),
        migrations.AddField(
            model_name='securityfundamentals',
            name='day_high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='securityfundamentals',
            name='day_low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='securityfundamentals',
            name='exchange_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='securityfundamentals',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='securityfundamentals',
            name='price_avg_200',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='securityfundamentals',
            name='price_avg_50',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='securityfundamentals',
            name='year_high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='securityfundamentals',
            name='year_low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
