# Generated by Django 4.2.23 on 2025-08-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0006_remove_securityfundamentals_week_52_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityfundamentals',
            name='day_change_percent',
        ),
    ]
